local player = game:GetService("Players").LocalPlayer
local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "MohaESP_UI"
ScreenGui.IgnoreGuiInset = true
ScreenGui.ResetOnSpawn = false
ScreenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
ScreenGui.Parent = player:WaitForChild("PlayerGui")

local Label = Instance.new("TextLabel")
Label.Parent = ScreenGui
Label.Text = "Moha the Legend"
Label.Size = UDim2.new(0, 300, 0, 50)
Label.Position = UDim2.new(0, -300, 1, -100)
Label.BackgroundTransparency = 1
Label.TextColor3 = Color3.fromRGB(255, 255, 255)
Label.TextStrokeTransparency = 0
Label.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
Label.Font = Enum.Font.Garamond
Label.TextSize = 24
Label.TextXAlignment = Enum.TextXAlignment.Center
Label.TextYAlignment = Enum.TextYAlignment.Center